### ISSUE TITLE
Load state from server

### ISSUE THREAD

**Issue by m-a-r-i-a** [ivmartel/dwv-jqmobile#141]
Hi there,

We'd like to upgrade from version 0.27.0 to the newest one.

In the old version, we added the following code to `appgui.js` to load saved states from the server:

`app.addEventListener("loadend", function() {
var dwvState = new dwv.State(app);
$.ajax({
method: "GET",
url: "xyz",
dataType: "json"
}).then(function(data) {
dwvState.apply(app, data);
});
});`

As this code no longer works, something seems to have changed. In the current version, this error appears in the console: `dwv.State is not a constructor`

Can you please tell us how the above code has to be changed to get it working with the current version of DWV?

Thank you so, so much for your help in advance!

Best,

Maria

**Comment by ivmartel** [comment]
When you say newest, you mean `v0.32` ?
It's true I forgot to export the `State` class so the error makes sense. I can publish a `v0.32.1` with the state export, is that the only problem you're having?

**Comment by m-a-r-i-a** [comment]
Yes, we're talking about `v0.32`.

It would be wonderful if you could include the `State` class. All other things work perfect.

**Comment by ivmartel** [comment]
Ok, done! I published dwv v0.32.1 that now allows to directly pass the state json to the app with `app.applyJsonState(json)`

**Comment by m-a-r-i-a** [comment]
Thank you for the quick update!

I'm currently still seeing `v0.32` as latest release and can't see `v0.32.1` yet. Maybe GitHub needs a moment to update ...

**Comment by ivmartel** [comment]
I did not update dwv-jqmobile yet. The new dwv is available on npm.

**Comment by m-a-r-i-a** [comment]
Okay, I see. It would be great if you could please update dwv-jqmobile as well when you get a chance.

Many thanks for your efforts!

**Comment by ivmartel** [comment]
Ok, done in the latest code of this repo!

If you could share what your project is about, I'm interested.

**Comment by m-a-r-i-a** [comment]
Thanks for the quick update!

I'll take a look at your new release as soon as possible.

We are a veterinary practice and work mainly mobile. DWV is a great help for us to be able to view X-rays of our patients on smartphones and tablets.

**Comment by m-a-r-i-a** [comment]
I just wanted to confirm that everything is working well.

Many, many thanks for the absolutely impressive work! DWV is a wonderful tool and we really appreciate your work.
